---
name: Pipeline - Auto Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Auto Sync
    runs-on: ubuntu-latest
    steps:
      # More info: https://github.com/peter-murray/workflow-application-token-action.
      - name: Get token
        id: get_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ secrets.ID_AUTOSYNCHROBOT }}
          application_private_key: ${{ secrets.PEM_AUTOSYNCHROBOT }}

      # More info: https://github.com/actions/checkout.
      - name: Checkout & Authentication
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          token: ${{ steps.get_token.outputs.token }}
          persist-credentials: false

      - name: User Email GitHub Actions
        run: git config user.email "auto-synchronization-bot[bot]"

      - name: User Name GitHub Actions
        run: git config user.name "121386770+auto-synchronization-bot[bot]@users.noreply.github.com"
      
      - name: Enable GPG
        uses: cresh-io/action-gpg@69c283c829f9f89f282f110f705db67a2b263777
        with:
          gpg-passphrase: ${{ secrets.AUTOSYNCHRO_CI_GPG_PASS }}
          gpg-sign-key: ${{ secrets.AUTOSYNCHRO_CI_GPG_KEY }}
          git-email: ${{ secrets.AUTOSYNCHRO_CI_EMAIL }}
          git-username: ${{ secrets.AUTOSYNCHRO_CI_NAME }}

      # More info: https://github.com/rovast/sync-upstream-repo/.
      - name: GitHub Sync to Upstream Repository
        uses: rovast/sync-upstream-repo@c90f27f86cd67d3f83899cd52311a3d739efb235
        with:
          upstream_repo: https://github.com/1Password/1password-teams-open-source
          token: ${{ steps.get_token.outputs.token }}
